version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fullstack-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - .env
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - fullstack-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    networks:
      - fullstack-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - fullstack-network

volumes:
  mysql_data:

networks:
  fullstack-network:
